(function(){
'use strict';
const KEY='trivial-electricista-review-flags-v8';
function read(k){try{return JSON.parse(localStorage.getItem(k)||'{}')}catch(e){return {}}}
let flags=read(KEY);Object.assign(flags,read('trivial-electricista-review-flags-v7'),read('trivial-electricista-review-flags-v6'));
function save(){try{localStorage.setItem(KEY,JSON.stringify(flags))}catch(e){}}
function norm(s){return String(s||'').replace(/\s+/g,' ').trim().toLowerCase()}
function esc(s){return String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
const css=`#te-review-menu-button{background:#444;color:#fff;border:0;border-radius:10px;padding:10px 14px;font-weight:800;width:100%;margin-top:8px}#te-review-badge{background:#d32f2f;color:#fff;border-radius:999px;padding:3px 8px;font-size:12px}#te-question-mark{background:#ffd54a;color:#20170b;border:0;border-radius:9px;padding:10px 14px;font-weight:800;display:block;width:100%;box-sizing:border-box;margin-bottom:8px}#te-question-mark.marked{background:#6b4a2d;color:#fff}#te-review-panel{position:fixed;inset:0;background:#000b;z-index:100000;display:none;align-items:center;justify-content:center;padding:12px}#te-review-panel.show{display:flex}#te-review-panel .box{background:#2a1c11;color:#fff;border:3px solid #a97939;border-radius:16px;padding:18px;max-width:760px;width:100%;max-height:88vh;overflow:auto}#te-review-panel h2{color:#ffd54a}#te-review-panel .item{padding:12px;margin:8px 0;border:1px solid #6b4a2d;border-radius:10px;background:#1b120b}#te-review-panel .row{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}#te-review-panel button{background:#ffd54a;border:0;border-radius:8px;padding:7px 10px;font-weight:bold}#te-review-panel button.remove{background:#555;color:#fff}`;
function style(){if(!document.getElementById('te-review-css')){let s=document.createElement('style');s.id='te-review-css';s.textContent=css;document.head.appendChild(s)}}
function question(){let m=document.getElementById('questionModal'),t=document.getElementById('questionText');if(!m||!t)return null;let q=(t.textContent||'').trim();if(!q)return null;return{q:q,cat:(document.getElementById('questionTitle')?.textContent||'').trim(),key:norm(q)}}
function count(){return Object.keys(flags).length}
function refresh(){let n=count();document.querySelectorAll('#te-review-badge').forEach(x=>{x.textContent=n;x.style.display=n?'inline-block':'none'});let b=document.getElementById('te-question-mark'),q=question();if(b&&q){let on=!!flags[q.key];b.textContent=on?'✓ Marcada para revisar':'⚠️ Marcar para revisar';b.classList.toggle('marked',on)}}
function mark(){let q=question();if(!q)return;if(flags[q.key])delete flags[q.key];else flags[q.key]={question:q.q,category:q.cat,markedAt:Date.now()};save();refresh()}
function ensureQuestionButton(){let m=document.getElementById('questionModal'),a=m?.querySelector('.actions'),q=question();if(!m||!a||!q)return;if(!document.getElementById('te-question-mark')){let b=document.createElement('button');b.id='te-question-mark';b.type='button';b.onclick=function(e){e.preventDefault();e.stopPropagation();mark()};a.insertBefore(b,a.firstChild)}refresh()}
function visible(e){if(!e)return false;let r=e.getBoundingClientRect(),s=getComputedStyle(e);return s.display!='none'&&s.visibility!='hidden'&&r.width>0&&r.height>0}
function menu(){let bs=[...document.querySelectorAll('button,a')],m=bs.find(x=>visible(x)&&/^\s*(☰|≡)?\s*menú\s*$/i.test(x.innerText||x.textContent||''));if(!m)return null;let p=m.parentElement;for(let i=0;p&&i<8;i++,p=p.parentElement){let t=norm(p.innerText||'');if(p.querySelectorAll('button,a').length>=2&&/nueva partida|editor|jugadores|salir/.test(t))return p}return null}
function panel(){let p=document.getElementById('te-review-panel');if(!p){p=document.createElement('div');p.id='te-review-panel';document.body.appendChild(p)}return p}
function openPanel(){let p=panel(),items=Object.entries(flags);p.innerHTML='<div class="box"><h2>⚠️ Preguntas marcadas para revisar</h2>'+(items.length?items.map(([k,v])=>'<div class="item"><b>'+esc(v.category||'Pregunta')+'</b><div>'+esc(v.question||'')+'</div><div class="row"><button data-e="'+encodeURIComponent(k)+'">✏️ Editar</button><button class="remove" data-r="'+encodeURIComponent(k)+'">✓ Quitar marca</button></div></div>').join(''):'<p>No hay preguntas marcadas.</p>')+'<button id="te-review-close">Cerrar</button></div>';p.classList.add('show');p.querySelector('#te-review-close').onclick=()=>p.classList.remove('show');p.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{delete flags[decodeURIComponent(b.dataset.r)];save();refresh();openPanel()});p.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>edit(decodeURIComponent(b.dataset.e)))}
function edit(k){let p=document.getElementById('te-review-panel');if(p)p.classList.remove('show');let d=window.TRIVIAL_DATABASE;if(Array.isArray(d)){let i=d.findIndex(x=>norm(x.q)===k);if(i>=0&&typeof window.openFullDatabaseEditor==='function'){window.openFullDatabaseEditor(i);return}}let s=document.getElementById('searchQ');if(s){s.value=(flags[k]||{}).question||'';if(window.DBPagination?.apply)window.DBPagination.apply()}}
function installMenu(){let m=menu();if(!m)return;let b=document.getElementById('te-review-menu-button');if(!b){b=document.createElement('button');b.id='te-review-menu-button';b.type='button';b.innerHTML='⚠️ Revisar marcadas <span id="te-review-badge"></span>';b.onclick=e=>{e.preventDefault();e.stopPropagation();openPanel()};let a=m.querySelector('.actions');(a||m).appendChild(b)}refresh()}
function boot(){style();panel();let run=()=>{ensureQuestionButton();installMenu()};[0,100,300,700,1200].forEach(x=>setTimeout(run,x));let ob=new MutationObserver(run);ob.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['class','style']});document.addEventListener('click',()=>setTimeout(run,0),true);window.addEventListener('pageshow',run);window.addEventListener('load',run);refresh()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
